#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin site-install

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Copy a settings file.
# Skips if the destination file already exists.
# @param $1 source file
# @param $2 destination file
copy_settings_file()
{
	local source="$1"
	local dest="$2"

	if [[ ! -f $dest ]]; then
		echo "Copying ${dest}..."
		cp $source $dest
	else
		echo "${dest} already in place."
	fi
}

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------

# Initialize docroot
init_docroot ()
{
	cd ${PROJECT_ROOT}

	sudo rm -rf ${DOCROOT}
	unzip ./.docksal/drupal/drupal-8.5.x.zip -d ${DOCROOT}
	cp ./.docksal/drupal/example.gitignore ${DOCROOT}/.gitignore
	#git apply -v ./.docksal/drupal/settings.patch
	cd ${DOCROOT} && git pull
}

# Initialize local settings files
init_settings ()
{
	# Copy from settings templates
	copy_settings_file "${PROJECT_ROOT}/.docksal/drupal/settings.php" "${SITEDIR_PATH}/settings.php"
	copy_settings_file "${PROJECT_ROOT}/.docksal/drupal/settings.local.php" "${SITEDIR_PATH}/settings.local.php"
}

# Fix file/folder permissions
fix_permissions ()
{
	echo "Making site directory writable..."
	chmod 755 "${SITEDIR_PATH}"
}

# Install site
site_install ()
{
	cd $DOCROOT_PATH

	# Use drupal console instead of drush (drush currently has issues installing Drupal 8.4)
	drupal site:install  standard  --force --no-interaction \
		--langcode="en"  \
		--db-type="mysql"  \
		--db-host="db"  \
		--db-name="default"  \
		--db-user="user"  \
		--db-pass="user"  \
		--db-port="3306"  \
		--site-name="My Drupal 8 Site"  \
		--site-mail="admin@example.com"  \
		--account-name="admin"  \
		--account-mail="admin@example.com"  \
		--account-pass="password"
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

# Project initialization steps
init_docroot
init_settings
fix_permissions
time site_install

#-------------------------- END: Execution --------------------------------
